auctions/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index_view, name="index"),
    # path("login", LoginView.as_view(template_name="auctions/login.html"), name="login"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register_view, name="register"),
    path("categories", views.categories_view, name="categories"),
    path("watchlist", views.watchlist_view, name="watchlist"),
    path("create listing", views.create_listing_view, name="create listing"),
    path("closed listings", views.closed_listings_view, name="closed listings")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass


class Listing(models.Model):
   id = ...
   listing_title = ...
   description = ...
   min_price = ...
   image = ...
   category = ...
   user_id = ...

# class bids():
# class comments():u

auctions/forms.py
from django.forms import ModelForm
from django import forms
from .models import Listing


class NewListingForm(ModelForm):
    # title
    listing_title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Title'}))
    # text-based description
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Description', 'rows': 4, 'cols': 40}))
    # starting bid price
    min_price = forms.DecimalField(widget=forms.TextInput(attrs={'placeholder': 'Price'}))
    # optionally image URL
    image = forms.URLField(widget=forms.TextInput(attrs={'placeholder': 'Image URL'}), blank=True)
    # optionally category
    category = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Category'}), blank=True)

    class Meta:
        model = Listing
        fields = ['listing_title', 'description', 'min_price', 'image', 'category']

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django import forms

from .models import User
from .forms import NewListingForm

# class NewListingForm(forms.Form):
#     # title
#     listing_title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Title'}))
#     # text-based description
#     description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Description', 'rows': 4, 'cols': 40}))
#     # starting bid price
#     min_price = forms.DecimalField(widget=forms.TextInput(attrs={'placeholder': 'Price'}))
#     # optionally image URL
#     image = forms.URLField(widget=forms.TextInput(attrs={'placeholder': 'Image URL'}), blank=True)
#     # optionally category
#     category = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Category'}), blank=True)


def index_view(request):
    return render(request, "auctions/index.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")


def categories_view(request):
    return render(request, "auctions/categories.html")


def watchlist_view(request):
    # if no user is signed in, return to login page:
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("auctions:login"))
    return render(request, "auctions/watchlist.html")


def create_listing_view(request):
    if request.method == "POST":
        # Take in the data the user submitted and save it as form
        form = NewListingForm(request.POST)

        # check if form data is valid (server-side)
        if form.is_valid():

            # here insert what to do when the form is valid
            print("Here will be an action about what to do when the form is valid.")
            listing_title = form.cleaned_data["New listing title"]
            # text-based description
            description = form.cleaned_data["Description"]
            # starting bid price
            min_price = form.cleaned_data["Starting price"]
            # optionally image URL
            image = form.cleaned_data["Image link"]
            # optionally category
            category = form.cleaned_data["Category"]
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            # if the form is invalid, re-enter the page with existing information.
            return render(request, "auctions/create_listing.html", {
                "form": form
            })

    # if the user is not authenticated, redirect to login with the next param
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("auctions:login"))

    return render(request, "auctions/create_listing.html", {
        "form": NewListingForm()
    })


def closed_listings_view(request):
    return render(request, "auctions/closed_listings.html")

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}

    <div>Here will be a list of categories.</div>

{% endblock %}

auctions/templates/auctions/closed_listings.html
{% extends "auctions/layout.html" %}

{% block body %}


    <div>Here will be a list of closed listings.</div>


{% endblock %}

auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h3>New listing:</h3>
    <form action="{% url 'auctions:create listing' %}" method="POST">
        {% csrf_token %}

        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}

        {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field }}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Submit</button>
{#        {{ form }}#}
    </form>
    <a href="{% url 'auctions:index' %}">View Listings</a>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>

    TODO
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet " href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:closed listings' %}">Closed Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:create listing' %}?next={{ request.path }}">Create Listing</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}

    <div>Here will be a watchlist.</div>

{% endblock %}